name: nba-lineup-optimizer
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - ca-certificates=2020.12.5
  - catboost=0.24.3
  - certifi=2020.12.5
  - cffi=1.14.4
  - click=7.1.2
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.4
  - importlib-metadata=3.3.0
  - importlib_metadata=3.3.0
  - ipykernel=5.4.2
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.2
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.3
  - mistune=0.8.4
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.1.6
  - numpy=1.19.4
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.2.0
  - pandoc=2.11.3.1
  - pandocfilters=1.4.2
  - parso=0.7.1
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.3
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - python=3.8.6
  - python-dateutil=2.8.1
  - python-dotenv=0.15.0
  - python_abi=3.8
  - pytz=2020.5
  - pyzmq=20.0.0
  - readline=8.0
  - scipy=1.5.3
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.34.0
  - statsmodels=0.12.1
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.55.0
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
